name: Generate Version on Master Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

# Comment for test
jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      
      - name: Collect issue numbers since last release/tag in master
        continue-on-error: true
        run: |
          
          export LC_ALL=en_US.utf8
          
          start_sha=$(git describe --abbrev=0 --tags main 2> /dev/null || \
            git rev-list --max-parents=0 HEAD)
          grabbed_changes=$(git rev-list --pretty=oneline $start_sha..HEAD)
          
          echo Processed Commits:
          echo $grabbed_changes
          echo $start_sha

          git rev-list --pretty=oneline $start_sha..HEAD | grep -oE "WPD-[[:digit:]]{1,}" | sort | uniq | sed 's/^\|$/"/g' | paste -sd , | awk '{print "RELATED_JIRA_ISSUES="$0}' >> $GITHUB_ENV
        shell: bash

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: "opploans-"
          skip-on-empty: false
          skip-commit: true
          create-summary: true
          fallback-version: "opploans-0.1.0"

      - name: Get Current Date
        run: |
          current_date=$(date +'%Y-%m-%d')
          echo ${{env.RELATED_JIRA_ISSUES}}
          echo "CURRENT_DATE=$current_date" >> "$GITHUB_ENV"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: '${{ steps.changelog.outputs.tag }} (${{ env.CURRENT_DATE }})'
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          generateReleaseNotes: true
